const nameList = [
  "Alex",
  "Sophia",
  "Ethan",
  "Olivia",
  "Liam",
  "Emma",
  "Jackson",
  "Ava",
  "Lucas",
  "Isabella",
  "Mia",
  "Aiden",
  "Layla",
  "Caden",
  "Ella",
  "Noah",
  "Nora",
  "Mason",
  "Lily",
  "Logan",
  "Zoe",
  "Caleb",
  "Chloe",
  "Wyatt",
  "Emily",
  "Jayden",
  "Madison",
  "Oliver",
  "Amelia",
  "Elijah",
  "Abigail",
  "Avery",
  "Grace",
  "Benjamin",
  "Harper",
  "Henry",
  "Scarlett",
  "Samuel",
  "Aria",
  "David",
  "Victoria",
  "Sophie",
  "Christopher",
  "Evelyn",
];

export function randomNameGenerate() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const words = [
  "Lorem",
  "ipsum",
  "dolor",
  "sit",
  "amet",
  "Hi",
  "Hello",
  "Hey",
  "Great",
  "Amazing",
  "Impressive",
  "Superb",
  "Excellent",
  "Cool",
  "Wonderful",
  "Nice",
  "Brilliant",
  "Incredible",
  "Fabulous",
  "Terrific",
  "Outstanding",
  "Howdy",
  "Yo",
  "Greetings",
  "Sup",
  "What's up?",
  "Good day",
  "Hi there",
  "Hey there",
  "Marvelous",
  "Good",
  "Splendid",
  "Outstanding",
  "Magnificent",
  "Lovely",
  "Beautiful",
  "Stunning",
  "Rad",
  "Fantastic",
  "Phenomenal",
  "Remarkable",
  "Spectacular",
  "Top-notch",
  "Mind-blowing",
  "Astounding",
  "Awe-inspiring",
  "Dazzling",
  "Greetings!",
  "How's it going?",
  "What's new?",
  "Hey friend",
  "Hola",
  "Bonjour",
  "Ciao",
  "Namaste",
  "Salut",
  "Hola amigo",
  "Sup fam",
  "Greetings and salutations",
  "Hiya",
  "Hey you!",
  "Hey buddy",
  "Good to see you",
  "How are you?",
  "Long time no chat",
  "Wassup?",
  "Hey stranger",
  "Hi friend",
  "Cheers!",
];

export function generateRandomMessage() {
  const messageLength = Math.floor(Math.random() * 2) + 3;
  const randomMessage = [];

  for (let i = 0; i < messageLength; i++) {
    const randomIndex = Math.floor(Math.random() * words.length);
    randomMessage.push(words[randomIndex]);
  }

  return randomMessage.join(" ");
}
